<?php

  // Summary
  //
  // We have two menu items. The first one builds the form by calling drupal_get_form and creates a link to it in the Navigation menu. The second one's URL is called by the submit function to display the success page after the solution is calculated.
  //
  // The function ping_pong_form creates a form with one text field for the goal number and a submit button.
  //
  // All of the processing of data to figure out the solution happens in the submit function.
  //
  // We save the results as a session variable.
  //
  // We set the form's 'redirect' property to lead to our success page at the URL defined in the second menu item.
  //
  // Declare the function defined as the success page's menu item's callback: ping_pong_success.
  //
  // Inside of the success function, get the results back out of the session variable and print them.

function ping_pong_menu() {
    $items = array();
    $items['ping_pong'] = array(
        'title' => 'Ping Pong Problem',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['ping_pong_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'ping_pong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function ping_pong_form() {
    $form['count_goal'] = array(
        '#title' => 'Count Goal',
        '#type' => 'textfield',
        '#description' => t('Please enter the number you want to count up to.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function ping_pong_form_submit($form, &$form_state) {

    $count_max = $form_state['values']['count_goal'];
    $pingpong_output = array();

    for ($i=1; $i <= $count_max; $i++) {
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($pingpong_output, "ping-pong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");
        } else {
            array_push($pingpong_output, $i);
        }
    }

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'ping_pong_success_page';
}

function ping_pong_success() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }
    $output = $output . '</ul>';
    return "Yippie! $output";
}
